version: "3.7"
services:
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: intertienda_back_v1
        container_name: intertienda_back_v1-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - .:/var/www
        networks:
            - intertienda_back_v1

    db:
        image: mysql:5.7
        container_name: intertienda_back_v1-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: intertienda_back_v1_db
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_PASSWORD: 12345
            MYSQL_USER: docker_user
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker/mysql/data_db:/var/lib/mysql
        networks:
            - intertienda_back_v1

    nginx:
        image: nginx:alpine
        container_name: intertienda_back_v1-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - .:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - intertienda_back_v1

networks:
    intertienda_back_v1:
        driver: bridge
#https://www.digitalocean.com/community/tutorials/how-to-install-and-set-up-laravel-with-docker-compose-on-ubuntu-20-04-es
